# Generated by Django 4.2.5 on 2023-09-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='update',
            new_name='updated',
        ),
    ]
